---
title: "Dashboard Precariedad EPH"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(eph)
library(plotly)
library(tidyverse)
base <- get_microdata(year = 2023,period = 4)

precariedad_rama <- base %>%
  organize_caes() %>%
  mutate(PONDIIO = as.numeric(PONDIIO)) %>% #Evitar integer overflow
  filter(ESTADO == 1, CAT_OCUP == 3) %>% 
  group_by(TRIMESTRE,ANO4,caes_eph_label) %>% 
  summarise(asalariados = sum(PONDERA,na.rm = T),
            salario_prom = weighted.mean(P21,PONDIIO,na.rm = T),
            registrados = sum(PONDERA[PP07H == 1],na.rm = T),
            no_registrados = sum(PONDERA[PP07H == 2],na.rm = T),
            tasa_no_reg = no_registrados/asalariados) %>% 
  mutate(tasa_no_reg = round(tasa_no_reg,digits = 2),
         salario_prom = round(salario_prom,digits = 0))



```

Column {data-width=650}
-----------------------------------------------------------------------

### Precariedad laboral segun ramas 

```{r}
grafico_ramas <- ggplot(
  precariedad_rama,
  mapping = aes(x = tasa_no_reg,
                y = reorder(caes_eph_label,tasa_no_reg),
                fill = caes_eph_label,
                text = paste0(
                  "</br> Asalariados: ", asalariados,
                  "</br> Tasa No Reg: ",tasa_no_reg,
                  "</br> Salario Prom: ",salario_prom))
  )+
  geom_col()+
  labs(y = "",x= "Tasa de no registro")+ 
  theme(legend.position = "none")

ggplotly(grafico_ramas,tooltip = "text")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Precariedad por rama y sexo

```{r, warning=FALSE}
precariedad_rama_sexo <- base %>%
  organize_caes() %>%
  mutate(PONDIIO = as.numeric(PONDIIO),
         Sexo = ifelse(CH04 == 1,"Varón","Mujer")) %>%
  filter(ESTADO == 1, CAT_OCUP == 3) %>% 
  group_by(TRIMESTRE,ANO4,Sexo,caes_eph_label) %>% 
  summarise(asalariados = sum(PONDERA,na.rm = T),
            salario_prom = weighted.mean(P21,PONDIIO,na.rm = T),
            registrados = sum(PONDERA[PP07H == 1],na.rm = T),
            no_registrados = sum(PONDERA[PP07H == 2],na.rm = T),
            tasa_no_reg = no_registrados/asalariados) %>% 
  mutate(tasa_no_reg = round(tasa_no_reg,digits = 1),
         salario_prom = round(salario_prom,digits = 0)) %>% 
  ungroup()

precariedad_rama_sexo %>% 
  knitr::kable()
```
